### ISSUE TITLE
stackdriver/logging/write_data.go:55 cannot use d.Data (type interface {}) as type googleapi.RawMessage in assignment: need type assertion

### ISSUE THREAD

**Issue by bradleyfalzon** [evalphobia/google-api-go-wrapper#6]
Hi,

I'm trying to use https://github.com/evalphobia/logrus_stackdriver but getting the error:

```
go get -u github.com/evalphobia/logrus_stackdriver
# github.com/evalphobia/google-api-go-wrapper/stackdriver/logging
../../evalphobia/google-api-go-wrapper/stackdriver/logging/write_data.go:55:19: cannot use d.Data (type interface {}) as type googleapi.RawMessage in assignment: need type assertion
```

It looks like there was a breaking change in Google's API, which appears to have caused the issue: https://github.com/google/google-api-go-client/commit/b679263a6c5f7c6f7b66461aeb7ff4a0d0613278#diff-d043aaddb1338d7b5af2584effd1169aR680 (it's been changed since then too).

Is this something that can be resolved?

**Comment by evalphobia** [comment]
Thank you for your report.
I'll try to fix this in this weekend.

You can use old version of the`google/google-api-go-client` for work around, sorry for your inconvenience 😭

**Comment by bradleyfalzon** [comment]
Thanks for the quick response. And no inconvenience, I use your logrus sentry hook all the time, so appreciate the work you do maintaining these! ❤️

**Comment by evalphobia** [comment]
@bradleyfalzon Fixed code is merged 🐙 
If you can try to use the new version and confirm fixing, then please close PR!

**Comment by bradleyfalzon** [comment]
(btw I am testing this successfully, just debugging duplicate messages)

Edit: well, I'll close this, as the issue has been resolved. Thanks for this @evalphobia, much appreciated.
